import type { YcbStatementProfile, YcbStatementTransaction } from "./ycbStatementPreview";

const esc = (value: unknown) => String(value ?? "—").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
const money = (value: number | undefined) => Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function renderTadhamonFastStatement(profile: YcbStatementProfile, transactions: YcbStatementTransaction[], highlights: Record<string, string> = {}) {
  const rows = transactions.map((item) => {
    const color = /^#[0-9a-fA-F]{6}$/.test(highlights[item.reference] || "") ? highlights[item.reference] : "";
    const style = color ? ` style="--row-color:${color};background:${color}"` : "";
    const cell = (value: unknown, className = "") => `<td class="${className}"${style}>${esc(value)}</td>`;
    return `<tr${style}>${cell(item.date, "center")}${cell(item.reference, "center reference")}${cell(item.description)}${cell(item.credit ? money(item.credit) : "—", "amount")}${cell(item.debit ? money(item.debit) : "—", "amount")}${cell(money(item.balance), "amount balance")}</tr>`;
  }).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Tadhamon Bank — Quick Account Statement</title><style>
@page{size:A4 portrait;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#edf1f4;color:#111;font-family:Arial,Helvetica,sans-serif}.page{width:210mm;min-height:297mm;margin:0 auto;background:#fff;padding:10mm 11mm 8mm}.top{display:grid;grid-template-columns:1fr 1.4fr 1fr;gap:5mm;align-items:end;border-bottom:2px solid #b28a2e;padding-bottom:4mm}.top h1{font-size:16pt;text-align:center;margin:0 0 2mm}.top h2{font-size:10pt;text-align:center;margin:0;color:#164f92}.meta{font-size:9pt;line-height:1.7}.meta strong{display:block;color:#164f92}.meta.right{text-align:right}.summary{display:grid;grid-template-columns:repeat(4,1fr);margin:5mm 0 4mm;border:1px solid #b28a2e}.summary div{padding:2.5mm;text-align:center;border-right:1px solid #b28a2e;background:#fffbd7}.summary div:last-child{border-right:0}.summary span{display:block;font-size:8pt;font-weight:700}.summary strong{display:block;margin-top:1mm;font-size:11pt}.table{width:100%;border-collapse:collapse;font-size:8.4pt}.table th{background:#ef4b23;color:#fff;border:1px solid #8f2b16;padding:2.1mm;text-align:center}.table td{border:1px solid #777;padding:1.7mm;background:#ffed00;line-height:1.2}.table tr:nth-child(even) td{background:#fff}.table tr[style] td{background:var(--row-color)!important}.center{text-align:center}.amount{text-align:right;white-space:nowrap}.reference{font-family:monospace}.balance{font-weight:700}.footer{margin-top:5mm;display:flex;justify-content:space-between;font-size:8pt;border-top:1px solid #b28a2e;padding-top:2mm}.empty{padding:20mm;text-align:center;color:#777}@media print{html,body{background:#fff}.page{margin:0}}
</style></head><body><section class="page"><header class="top"><div class="meta"><strong>Account Number</strong>${esc(profile.accountNumber)}<strong>Customer</strong>${esc(profile.customerName)}</div><div><h1>TADHAMON BANK</h1><h2>Quick Account Statement</h2></div><div class="meta right"><strong>Branch</strong>${esc(profile.branchName)}<strong>Period</strong>${esc(profile.periodStart)} — ${esc(profile.periodEnd)}</div></header><section class="summary"><div><span>Opening Balance</span><strong>${money(profile.openingBalance)}</strong></div><div><span>Total Credit</span><strong>${money(profile.totalCredit)}</strong></div><div><span>Total Debit</span><strong>${money(profile.totalDebit)}</strong></div><div><span>Closing Balance</span><strong>${money(profile.closingBalance)}</strong></div></section>${transactions.length ? `<table class="table"><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Credit</th><th>Debit</th><th>Balance</th></tr></thead><tbody>${rows}</tbody></table>` : `<div class="empty">No accepted transactions have been imported.</div>`}<footer class="footer"><span>Tadhamon Bank — Quick Statement</span><span>Account: ${esc(profile.accountNumber)}</span><span>${esc(profile.issueDate)}</span></footer></section></body></html>`;
}

export function renderTadhamonFastStatementPages(profile: YcbStatementProfile, transactions: YcbStatementTransaction[], highlights: Record<string, string> = {}) {
  return renderTadhamonFastStatement(profile, transactions, highlights);
}
